"""empty message

Revision ID: 37838173c282
Revises: 76af1fa67c47
Create Date: 2020-03-27 10:02:35.432381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37838173c282'
down_revision = '76af1fa67c47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('club', sa.Column('join_code', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('club', 'join_code')
    # ### end Alembic commands ###
