"""empty message

Revision ID: 39480a1484c8
Revises: 92089a34d190
Create Date: 2020-03-18 09:52:19.912491

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '39480a1484c8'
down_revision = '92089a34d190'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club_owners',
                    sa.Column('club_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('club_id', 'user_id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('club_owners')
    # ### end Alembic commands ###
