"""empty message

Revision ID: 76af1fa67c47
Revises:
Create Date: 2020-03-24 17:33:05.888490

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '76af1fa67c47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('club',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=True),
                    sa.Column('registered_school', sa.Text(), nullable=True),
                    sa.Column('school_verified', sa.Boolean(), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('user',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.Text(), nullable=False),
                    sa.Column('username', sa.Text(), nullable=False),
                    sa.Column('email', sa.Text(), nullable=False),
                    sa.Column('password_hash', sa.Text(), nullable=False),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.Column('email_verified', sa.Boolean(), nullable=True),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('administrators',
                    sa.Column('club_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('club_id', 'user_id')
                    )
    op.create_table('chat_message_thread',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('last_active', sa.DateTime(), nullable=False),
                    sa.Column('user_count', sa.Integer(), nullable=False),
                    sa.Column('club_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('club_members',
                    sa.Column('club_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('club_id', 'user_id')
                    )
    op.create_table('club_owners',
                    sa.Column('club_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['club_id'], ['club.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('club_id', 'user_id')
                    )
    op.create_table('training_session',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('start_time', sa.DateTime(), nullable=True),
                    sa.Column('end_time', sa.DateTime(), nullable=True),
                    sa.Column('livestream', sa.Boolean(), nullable=False),
                    sa.Column('description', sa.Text(), nullable=True),
                    sa.Column('club', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['club'], ['club.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('chat_message',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('thread_id', sa.Integer(), nullable=True),
                    sa.Column('is_reply', sa.Boolean(), nullable=False),
                    sa.Column('reply_to', sa.Integer(), nullable=True),
                    sa.Column('created', sa.DateTime(), nullable=False),
                    sa.ForeignKeyConstraint(['reply_to'], ['chat_message.id'], ),
                    sa.ForeignKeyConstraint(['thread_id'], ['chat_message_thread.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_table('training_session_attendance',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('training_session_id', sa.Integer(), nullable=False),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.Column('attending', sa.Boolean(), nullable=False),
                    sa.ForeignKeyConstraint(['training_session_id'], ['training_session.id'], ),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('training_session_attendance')
    op.drop_table('chat_message')
    op.drop_table('training_session')
    op.drop_table('club_owners')
    op.drop_table('club_members')
    op.drop_table('chat_message_thread')
    op.drop_table('administrators')
    op.drop_table('user')
    op.drop_table('club')
    # ### end Alembic commands ###
