"""empty message

Revision ID: 989de7ed4f21
Revises: e1c5cefd1c0e
Create Date: 2020-03-24 17:07:58.502381

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '989de7ed4f21'
down_revision = 'e1c5cefd1c0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_message', sa.Column('thread_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat_message', 'chat_message', ['reply_to'], ['id'])
    op.create_foreign_key(None, 'chat_message', 'chat_message_thread', ['thread_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_message', type_='foreignkey')
    op.drop_constraint(None, 'chat_message', type_='foreignkey')
    op.drop_column('chat_message', 'thread_id')
    # ### end Alembic commands ###
