"""empty message

Revision ID: c6bd6765c9f9
Revises: 39480a1484c8
Create Date: 2020-03-18 11:14:55.819143

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'c6bd6765c9f9'
down_revision = '39480a1484c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_verified', sa.Boolean(), nullable=False))
    op.alter_column('user', 'created',
                    existing_type=sa.DATETIME(),
                    nullable=False)
    op.alter_column('user', 'email',
                    existing_type=sa.TEXT(),
                    nullable=False)
    op.alter_column('user', 'name',
                    existing_type=sa.TEXT(),
                    nullable=False)
    op.alter_column('user', 'password_hash',
                    existing_type=sa.TEXT(),
                    nullable=False)
    op.alter_column('user', 'username',
                    existing_type=sa.TEXT(),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
                    existing_type=sa.TEXT(),
                    nullable=True)
    op.alter_column('user', 'password_hash',
                    existing_type=sa.TEXT(),
                    nullable=True)
    op.alter_column('user', 'name',
                    existing_type=sa.TEXT(),
                    nullable=True)
    op.alter_column('user', 'email',
                    existing_type=sa.TEXT(),
                    nullable=True)
    op.alter_column('user', 'created',
                    existing_type=sa.DATETIME(),
                    nullable=True)
    op.drop_column('user', 'email_verified')
    # ### end Alembic commands ###
