name: Test backend

on:
  push:
    paths:
    - "backend/**/*"

jobs:
  tests:
    name: Rust project
    runs-on: ubuntu-latest
    steps:
      - run: cd backend
      - uses: actions/checkout@master
      - uses: actions-rs/cargo@v1
        with:
          command: build