name: Test backend
on:
  push:
    paths:
    - "backend/**/*"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Run tests
      working-directory: ./backend
      uses: actions-rs/cargo@v1
      with:
        command: test
