name: Deploy

on:
  push:
    paths:
    - "client/**/*"
    - "docs/**/*"

jobs:
  build-web-app:
    name: Build the web app
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x

    - name: Install dependencies
      run: |
        cd client
        yarn install
        cd ../

    - name: Build site
      run: |
        cd client
        expo build:web

    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: web-build
        path: client/web-build

  build-documentation:
    name: Build the documentation
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Install dependencies
      run: wget -q -O - "https://github.com/getzola/zola/releases/download/v0.9.0/zola-v0.9.0-x86_64-unknown-linux-gnu.tar.gz" | sudo tar xzf - -C /usr/local/bin
    - name: Build site
      run: |
        cd docs
        zola build
    - name: Upload artifact
      uses: actions/upload-artifact@v1
      with:
        name: doc-build
        path: docs/public

  deploy-firebase:
    name: Deploy to Firebase Hosting
    runs-on: ubuntu-latest
    needs: [build-documentation, build-web-app]
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Download documentation build
      uses: actions/download-artifact@v1
      with:
        name: doc-build
    - name: Download web app build
      uses: actions/download-artifact@v1
      with:
        name: web-build
    - name: Configure directory structure
      run: |
        mv web-build public
        mv doc-build public/docs
    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}




