name: Firebase deploy

on: [push]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    - name: Install Dependencies
      run: npm install --prefix app && npm install --prefix functions
    - name: Build
      run: npm run build --prefix app
    - name: Deploy to firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
